exclude: 'docs|tex|.dat|.mod|test'
# include: '.py'
repos:
-   repo: meta
    hooks:
    -   id: identity
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.0
    hooks:
    -   id: autoflake
        args: [--in-place, --expand-star-imports]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
    -   id: ruff
        args: [--config=./pyproject.toml, --fix]
    -   id: ruff-format


# -   repo: https://github.com/pre-commit-pre-commit-hooks